[package]
name = "microkernel"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.10.2"
spin = "0.9.4"  # For synchronization and lock primitives

[build-dependencies]
bootimage = "0.10.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
