[package]
name = "microkernel"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.11.7"  # Latest stable version of bootloader
spin = "0.9.8"  # Synchronization primitives


[build-dependencies]
bootimage = "0.10.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
